### ISSUE TITLE
Zoom out not possible when using minified version

### ISSUE THREAD

**Issue by mik13ST** [SpencerWie/Panzoom#3]
There are three demos given. The first two work fine but zooming out on the third one doesn't work. This was also happening in my own code. The difference between the demos is the third one uses the minified version of the library (`../../dist/panzoom.min.js`). I confirmed this to be the cause by changing to non-minified version in my code which fixed the issue.

My browser is Firefox ESR 115.11.

Here are the demos copied from Readme.md.
[Demo using HTML 5 Canvas](https://rawcdn.githack.com/SpencerWie/Panzoom/fe4fb6af7595c4db3c1489a82884a6d1cdbbd4f6/demo/CanvasExample/index.html)
    [Demo using SVG Image](https://rawcdn.githack.com/SpencerWie/Panzoom/fe4fb6af7595c4db3c1489a82884a6d1cdbbd4f6/demo/SvgExample/index.html)
    [Demo using DIV Tag](https://rawcdn.githack.com/SpencerWie/Panzoom/b793c3b0f76a190f55f62108b6676147b3452b5f/demo/DivExample/index.html)

Which minifier is this project using?

**Comment by SpencerWie** [comment]
Thanks for bringing this up @mik13ST yes I've confirmed that on Firefox this is an issue but on Chrome it works fine. It's been quite awhile since I minified this code so I couldn't tell you exactly what I used, likely a random one I found in Google, but I'll redo the example.

**Comment by SpencerWie** [comment]
@mik13ST  I've re-minified the code and updated the demos to point to master, it's possible it was a problem due it being pointing to an older commit. The issue is now resolved.
